### ISSUE TITLE
Xcode 6下编译失败

### ISSUE THREAD

**Issue by tomisacat** [singro/v2ex#11]
Xcode 6.2(6C131e) 编译失败，提示
![b985bc75-0114-4051-92ec-b89921029677](https://cloud.githubusercontent.com/assets/1179735/8125813/9cf3389c-111b-11e5-87f2-73d8ae2f80cc.png)
 将 Target -> Build Settings -> Build Active Architecture Only 改为 YES 编译，提示：
Shell Script Invocation Error: Command /bin/bash failed with exit code 1 并且浏览器自动打开了 fabric 首页。不知道是否是 fabric 和 bash 产生了冲突？

**Comment by SeanChense** [comment]
https://github.com/singro/v2ex/issues/15

**Comment by yuldong** [comment]
完美的解决了这个问题,也不用去注册了

**Comment by tomisacat** [comment]
@SeanChense 多谢！
@yuldong 对
