### ISSUE TITLE
在pod install 时出现如下错误！

### ISSUE THREAD

**Issue by happy201993** [singro/v2ex#14]
![1](https://cloud.githubusercontent.com/assets/10241217/9354769/cd2f3730-46a5-11e5-8c74-3d5001a35a2b.jpg)

我的cocoapods 挂了？

**Comment by SeanChense** [comment]
我也是，升级到 0.38.2 前是正常 install 可是升级完了就这样了。

**Comment by singro** [comment]
最新的提交修复了这个问题， 修改了 Podfile

具体原因看：https://github.com/CocoaPods/CocoaPods/issues/3747
