### ISSUE TITLE
模拟器编译运行程序 浏览器会跳转到https://fabric.io/sign_up

### ISSUE THREAD

**Issue by iStig** [singro/v2ex#15]
XCode提示:
Fabric: This app relies on Fabric. Please sign up for access at https://fabric.io/sign_up,
install Fabric.app then ask a team member to invite you to this app's organization.

If this machine is a build server please remove Fabric.app if present and use xcodebuild so that v2ex-iOS.app.dSYM is uploaded.

**Comment by SeanChense** [comment]
下载一个 Fabric 注册登录一下，貌似什么都不用做就是可以编译了

**Comment by iStig** [comment]
谢谢，我试试。

**Comment by singro** [comment]
也可以在  `Target` -> `Build Phases` -> `Run Script` 去掉 fabric。
