### ISSUE TITLE
节点页面滑动起来感觉很卡，Cell里面都是button，好像复用的不是很好，不知道要怎么做了，求解答

### ISSUE THREAD

**Issue by XVXVXXX** [singro/v2ex#22]
节点页面滑动起来感觉很卡，Cell里面都是button，好像复用的不是很好，不知道要怎么做了，求解答。

**Comment by singro** [comment]
稍微优化了一下， 造成卡的主要原因还是因为离屏渲染。加上缓存一点点位置计算，但基本没差别；去掉 `clipsToBounds` 和 `cornerRadius`，加上数据的一点点变化，现在基本接近 60fps。
参考：
https://github.com/AttackOnDobby/iOS-Core-Animation-Advanced-Techniques/blob/master/15-图层性能/15-图层性能.md

**Comment by XVXVXXX** [comment]
我体验上来说，快速滑动节点页面还好，但是慢速滑动的时候，明显可以感受到cell在抖动啊...尤其是滑动到生活 这个section的时候，抖动很明显。设备：iphone6 iOS9，版本刚刚从appStore下了一个，慢滑滑不动。

**Comment by singro** [comment]
拉最新代码运行看看，比较流畅了已经。

**Comment by XVXVXXX** [comment]
就是最新的啊...最后一个merge还是我提的那个...难道是我手机有问题 ORZ，模拟器确实是不卡，不过硬件不一样啊

**Comment by XVXVXXX** [comment]
原来是button的圆角，真是没注意到，滑动确实不卡了。ps.你改的数据源有没改好一个地方，现在必crash啊，我改了一下。

**Comment by powfulhong** [comment]
我把圆角打开，没感觉有什么卡啊。。。圆角和背景图片没用上，感觉整个UI好难看。。。

**Comment by singro** [comment]
@powfulhong 节点页面加上圆角也还是能勉强接受的，仔细感觉下还是有点点不流畅。 如果把帖子列表打开圆角，感觉就差很多了

@XVXVXXX OK.. 随时欢迎各种优化、修复～
