### ISSUE TITLE
关于Manager类的一些问题？ 

### ISSUE THREAD

**Issue by zhou18520786640** [singro/v2ex#36]
非常感谢您的开源客户端。学到了很多东西，有几个问题想要请教你
V2DataManager负责所有请求参数的封装和请求发送，是否过于庞大？
相比较不进行封装 直接在具体的控制器中调用AFN的方法比起来，有什么好处？ 
Manager单独作为一个节点在工程中管理起来。Manager大部分是单例。算在MVC中到底属于哪一类？

**Comment by powfulhong** [comment]
网络请求就不要再放在C上了。。。C本来就很容易庞大起来，后面会很不好维护的。。。

**Comment by zhou18520786640** [comment]
@powfulhong ，那么Manager是自己根据需求抽出来的一层？ 它算MVC的一部分吗？ 全部写成单例？会不会没有太多东西暴露在外面？

**Comment by singro** [comment]
Manager 应该算在 M 里，统一写在一个地方是因为接口少，写一个地方方便管理。（如果接口比较多，可以考虑用 Category 区分不同的业务）
还有就是尽量不要把太多东西暴露在外面，给尽量少、足够用的到 C 就好了。

**Comment by zhou18520786640** [comment]
@powfulhong  @singro  谢谢两位
