### ISSUE TITLE
iPad上乱码问题

### ISSUE THREAD

**Issue by Mikey2008** [singro/v2ex#49]
![iPad乱码](https://cloud.githubusercontent.com/assets/20251016/22313322/6225928c-e397-11e6-877b-f45f6ff44171.PNG)
如图所示，乱码好几天了，之前在iPhone上没出现过，换iPad就这样了。

**Comment by singro** [comment]
iPad 的区域、语言有什么特别的设置么？ Safari 直接打开是否正常？

**Comment by Mikey2008** [comment]
时区、语言设置都没问题，Safari打开正常。
![Safari](http://imglf.nosdn.127.net/img/YW1mMVNMRFhFaEh2Y2VXcURCaEJndzVMOHlSNjFRWnF3Q1BNYXF0VkRET2QycG4vdmZYYTlBPT0.png)
卸载并重新安装应用问题依旧。
左侧菜单点击后右侧显示乱码，只有“节点”菜单点击可正常显示，乱码主题能点进去，可以正常显示帖子内容，退出帖子问题依旧——问题只出在主题贴list显示部分。

![节点](http://imglf2.nosdn.127.net/img/YW1mMVNMRFhFaEh2Y2VXcURCaEJnOEhTQkZvQXpsNFgvbHJmbjVvQlFVaXNrczVXczRRUHZBPT0.png)
![list乱码](http://imglf2.nosdn.127.net/img/YW1mMVNMRFhFaEh2Y2VXcURCaEJnOEhTQkZvQXpsNFhLYlY1VVdBVXUyNFM1Sk1PSXlvZVhRPT0.png)

没弄明白问题所在。
硬件环境：iPad mini2，系统最新iOS 10.2.1，其他APP如微博等显示正常，未测试同类V站的APP。

**Comment by SeanChense** [comment]
我也是 iPad 乱码

**Comment by CigarZh** [comment]
17款 ipad iOS 10.3 遇到同样问题
