### ISSUE TITLE
向您请教一个关于v2ex中SCActionSheet组件的问题

### ISSUE THREAD

**Issue by Brances** [singro/v2ex#57]
@singro 您好，我在研究您的源码时候出现了一点疑惑，如下图：
![image](https://user-images.githubusercontent.com/10275640/44438902-e73d7280-a5f3-11e8-85bf-dea6abbec1f7.png)
```
- (instancetype)sc_initWithTitles:(NSArray *)titles customViews:(NSArray *)customViews buttonTitles:(NSString *)buttonTitles, ... 
```
这是一个可变参数的实例方法，我想断点查看titles、customViews、buttonTitles 的值，不知道为什么一直显示nil

**Comment by singro** [comment]
看看 scheme 的设置， debug 才能看到值

**Comment by Brances** [comment]
@singro  大佬真是一语中的 点赞~
